"""Fetcher: напрямую → при недоступности хоста scrape.do (geoCode=ru), и это запоминается."""
import asyncio

import httpx
import pytest

from flight_bot.http import SCRAPEDO_URL, Fetcher


class _Resp:
    def __init__(self, text, status=200):
        self.text, self.status_code = text, status

    def raise_for_status(self):
        if self.status_code >= 400:
            raise httpx.HTTPStatusError("bad", request=None, response=None)


class _Client:
    """Фейковый httpx-клиент: dme.ru не пускает, scrape.do отвечает."""

    def __init__(self):
        self.calls = []

    async def get(self, url, params=None, timeout=None):
        self.calls.append((url, dict(params or {})))
        if url.startswith(SCRAPEDO_URL):
            return _Resp("<html>via scrape.do</html>")
        raise httpx.ConnectTimeout("blocked")


def test_falls_back_to_scrapedo_and_remembers():
    f = Fetcher(scrapedo_api_key="KEY")
    c = _Client()
    text = asyncio.run(f.get(c, "https://www.dme.ru/book/live-board/",
                             {"searchText": "S7 1055", "direction": "D"}))
    assert text == "<html>via scrape.do</html>"
    assert [u for u, _ in c.calls] == ["https://www.dme.ru/book/live-board/", SCRAPEDO_URL]
    p = c.calls[1][1]
    assert p["token"] == "KEY" and p["geoCode"] == "ru"
    # Кодировка пробела (+ или %20) — деталь httpx; проверяем разобранные параметры.
    from urllib.parse import parse_qs, urlsplit
    u = urlsplit(p["url"])
    assert (u.scheme, u.netloc, u.path) == ("https", "www.dme.ru", "/book/live-board/")
    assert parse_qs(u.query) == {"searchText": ["S7 1055"], "direction": ["D"]}
    assert f.via_proxy is True

    asyncio.run(f.get(c, "https://www.dme.ru/Ru/autogenerated/Flight/Detailed", {"id": "1"}))
    assert c.calls[-1][0] == SCRAPEDO_URL          # второй запрос сразу через scrape.do
    assert len(c.calls) == 3                        # без повторной попытки напрямую


def test_without_key_direct_error_propagates():
    f = Fetcher()
    with pytest.raises(httpx.ConnectTimeout):
        asyncio.run(f.get(_Client(), "https://www.dme.ru/book/live-board/"))
    assert f.via_proxy is False
