"""Источник: онлайн-табло Домодедово (DME). Server-render HTML, ключ не нужен.

Поиск по номеру (форма табло):
    GET https://www.dme.ru/book/live-board/?searchText=S7+1055&direction=D|A
Строка табло: план, факт (класс flightlate/flightcancel), номер, ГОРОД (только
русским названием, IATA нет), статус-строка, зона (терминал), id.
Детали по id (другой конец маршрута, тип ВС, факты):
    GET https://www.dme.ru/Ru/autogenerated/Flight/Detailed?id=<id>

Стоек, выхода, посадки, ленты табло не даёт — эти шаги остаются «ждём табло».
Все времена — московские (+03:00), как и у SVO.
"""
from __future__ import annotations

import html as _html
import re
from datetime import date, datetime, timedelta, timezone
from typing import Dict, List, Optional

from flight_bot.http import Fetcher
from flight_bot.models import FlightSnapshot, Leg
from flight_bot.sources.base import FlightSource

BASE_URL = "https://www.dme.ru/book/live-board/"
DETAIL_URL = "https://www.dme.ru/Ru/autogenerated/Flight/Detailed"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")
MSK = timezone(timedelta(hours=3))
MONTHS = {"янв": 1, "фев": 2, "мар": 3, "апр": 4, "мая": 5, "май": 5, "июн": 6,
          "июл": 7, "авг": 8, "сен": 9, "окт": 10, "ноя": 11, "дек": 12}
DIRECTION_PARAM = {"departure": "D", "arrival": "A"}

_ROW_RE = re.compile(r"<tr[^>]*>.*?</tr>", re.S)
_TD_RE = re.compile(r"<td\b([^>]*)>(.*?)</td>", re.S)
_WHEN_RE = re.compile(r"(\d{1,2})\s+([а-яё]{3})[а-яё]*\.?\s+(\d{1,2}):(\d{2})")


def _text(fragment: str) -> str:
    t = _html.unescape(re.sub(r"<[^>]+>", " ", fragment)).replace("\xa0", " ")
    return re.sub(r"\s+", " ", t).strip()


def _norm(flight_no: str) -> str:
    return flight_no.replace(" ", "").upper()


def _when(text: str, today: date) -> Optional[str]:
    """«5 сен 17:10» → ISO +03:00. Год — от today, декабрь→январь через границу."""
    m = _WHEN_RE.search(text)
    if not m:
        return None
    day, mon, hh, mm = int(m.group(1)), MONTHS.get(m.group(2)), int(m.group(3)), int(m.group(4))
    if not mon:
        return None
    year = today.year + (1 if mon == 1 and today.month == 12 else 0)
    return datetime(year, mon, day, hh, mm, tzinfo=MSK).isoformat()


def parse_board(page: str, flight_no: str, today: date) -> List[Dict]:
    """Строки табло с нужным номером. Чистый парсер — без сети."""
    wanted = _norm(flight_no)
    out: List[Dict] = []
    for row in _ROW_RE.findall(page):
        if 'class="timeflight"' not in row:
            continue
        tds = _TD_RE.findall(row)
        if len(tds) < 7:
            continue
        m = re.search(r"/>\s*([A-Z0-9]{2})\s*(\d{2,4})\s*</a>", tds[3][1])
        if not m or _norm(m.group(1) + m.group(2)) != wanted:
            continue
        rid = re.search(r"Detailed\?id=(\d+)", tds[3][1])
        li = re.search(r"<li>\s*(.*?)\s*</li>", tds[5][1], re.S)
        alt = re.search(r'alt="([^"]*)"', tds[3][1])
        out.append({
            "id": rid.group(1) if rid else "",
            "flight": m.group(1) + m.group(2),
            "airline": _html.unescape(alt.group(1)) if alt else "",
            "plan": _when(_text(tds[1][1]), today),
            "fact": _when(_text(tds[2][1]), today),
            "cancelled": "flightcancel" in tds[2][0],
            "city": _text(tds[4][1]).title(),
            "status": _text(li.group(1)) if li else _text(tds[5][1]),
            "zone": _text(tds[6][1]),
        })
    return out


def parse_detailed(page: str) -> Dict:
    """Диалог Detailed → маршрут, тип ВС, времена обоих концов (HH:MM), факты."""
    page = re.sub(r"<script.*?</script>", "", page, flags=re.S)
    t = re.sub(r"(\|\s*)+", " | ", _html.unescape(re.sub(r"<[^>]+>", "|", page)))
    t = re.sub(r"\s+", " ", t)

    def grab(pattern: str) -> str:
        m = re.search(pattern, t)
        return m.group(1).strip() if m else ""

    route = re.search(r"\|\s*([^|→]+?)\s*→\s*([^|]+?)\s*\|", t)
    return {
        "origin": route.group(1).strip() if route else "",
        "dest": route.group(2).strip() if route else "",
        "aircraft": grab(r"Тип воздушного судна \| ([^|]+)"),
        "dep": grab(r"Время отправления \| \([^)]*\) \| (\d{1,2}:\d{2})"),
        "dep_fact": grab(r"Вылетел в \| (\d{1,2}:\d{2})"),
        "arr": grab(r"Время прибытия \| \([^)]*\) \| (\d{1,2}:\d{2})"),
        "arr_fact": grab(r"(?:Прибыл|Совершил посадку|Приземлился)(?: в)? \| (\d{1,2}:\d{2})"),
    }


def _at(day_iso: Optional[str], hhmm: str, not_before: Optional[str] = None) -> Optional[str]:
    """HH:MM из Detailed на дату строки табло; если раньше not_before — следующий день."""
    if not day_iso or not hhmm:
        return None
    hh, mm = hhmm.split(":")
    d = datetime.fromisoformat(day_iso).replace(hour=int(hh), minute=int(mm), second=0)
    if not_before and d < datetime.fromisoformat(not_before):
        d += timedelta(days=1)
    return d.isoformat()


def build(row: Dict, det: Dict, direction: str) -> FlightSnapshot:
    """Строка табло + Detailed → снапшот. direction — чья сторона DME."""
    status = row["status"]
    st = status.lower()
    own_done = ("вылетел" in st) if direction == "departure" else \
               any(k in st for k in ("посадк", "прибыл", "прилетел"))
    # Факт-ячейка табло: при свершившемся событии это факт, иначе — оценка.
    own = Leg(plan=row["plan"],
              fact=row["fact"] if own_done else None,
              est=row["fact"] if (row["fact"] and not own_done and row["fact"] != row["plan"]) else None)
    if direction == "departure":
        arr_plan = _at(row["plan"], det.get("arr", ""), not_before=row["plan"])
        other = Leg(plan=arr_plan, fact=_at(row["plan"], det.get("arr_fact", ""), not_before=row["plan"]))
        departure, arrival = own, other
        origin_iata, origin_city, dest_iata, dest_city = "DME", "Москва", "", row["city"]
    else:
        other = Leg(plan=_at(row["plan"], det.get("dep", "")), fact=_at(row["plan"], det.get("dep_fact", "")))
        departure, arrival = other, own
        origin_iata, origin_city, dest_iata, dest_city = "", row["city"], "DME", "Москва"
    if row["cancelled"] and "отмен" not in st:
        status = "Рейс отменен"
    return FlightSnapshot(
        flight=row["flight"], date=(row["plan"] or "")[:10], direction=direction,
        origin_iata=origin_iata, dest_iata=dest_iata, status=status,
        departure=departure, arrival=arrival,
        airline=row["airline"], origin_city=origin_city, dest_city=dest_city,
        aircraft=det.get("aircraft", ""), terminal=row["zone"],
        source="dme.ru", key=row["id"],
    )


class DmeSource(FlightSource):
    name = "dme.ru"

    def __init__(self, scrapedo_api_key: str = "", timeout: float = 20.0):
        # dme.ru не пускает зарубежный адрес — Fetcher уводит в RU-прокси / scrape.do.
        self.fetcher = Fetcher(scrapedo_api_key, timeout=timeout)

    async def fetch(
        self,
        flight_no: str,
        date: Optional[str] = None,
        direction: str = "departure",
    ) -> List[FlightSnapshot]:
        no = _norm(flight_no)
        search = f"{no[:2]} {no[2:]}"              # табло ищет по «S7 1055», с пробелом
        today = datetime.now(MSK).date()
        page = await self.fetcher.get(BASE_URL, {
            "searchText": search, "direction": DIRECTION_PARAM[direction]})
        rows = [r for r in parse_board(page, no, today)
                if not date or (r["plan"] or "")[:10] == date]
        out = []
        for row in rows:
            det: Dict = {}
            if row["id"]:
                try:   # Detailed отдаётся и без XHR-заголовка — важно для прокси/scrape.do
                    det = parse_detailed(await self.fetcher.get(DETAIL_URL, {"id": row["id"]}))
                except Exception:  # noqa: BLE001 — без деталей строка табло всё равно полезна
                    det = {}
            out.append(build(row, det, direction))
        return out
